database:
  user: "meuse"
  password: "meuse"
  host: "127.0.0.1"
  port: 5432
  name: "meuse"
http:
  address: 127.0.0.1
  port: 8855
logging:
  level: debug
  console: true
  overrides:
    org.eclipse.jetty: info
    com.zaxxer.hikari.pool.HikariPool: info
    org.apache.http: error
    io.netty.buffer.PoolThreadCache: error
    org.eclipse.jgit.internal.storage.file.FileSnapshot: info
metadata:
  type: "shell"
  path: "/home/mathieu/prog/rust/testregistry"
  target: "origin/master"
  url: "https://github.com/mcorbin/testregistry"
crate:
  store: "filesystem"
  path: "/home/mathieu/prog/rust/crates"
frontend:
  enabled: true
  secret: uJo8QrRAANokteN_xVxpP75lc_A5Sw6t
  public: false
